# SPDX-License-Identifier: MIT
BLOCKSDS ?= /opt/blocksds/core
NAME := StarboundCourier
GAME_TITLE := Starbound Courier
GAME_SUBTITLE := AetherOS Original Game
GAME_SUBTITLE2 := Explore Collect Return
LIBS += -lnds9 -lc
include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
NDSTOOL_ARGS += -g QOSC 01 STARBOUNDCOR
